# Artificial Neural Network - Churn Modelling

## Life cycle of ANN Project

* 1) Data Preprocessing
* 2) Building the ANN
* 3) Training the ANN
* 4) Making the predictions and evaluating the model


## Problem Statement
* This project analyzes data from 10,000 bank customers to predict whether they will stay or leave the bank within a period of 6 months.

### Importing the libraries

In [116]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [117]:
tf.__version__

'2.9.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [118]:
dataset = pd.read_csv(r'D:\Online Courses\UDEMY\Machine_Learning/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [119]:
dataset.head(3)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1

#### Note:
* If Excited = 0 then the customer stay in the bank
* If Excited = 1 then the customer leaves the bank

In [120]:
dataset.shape

(10000, 14)

In [121]:
X.shape, y.shape

((10000, 10), (10000,))

In [122]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [123]:
dataset[['CreditScore','Age','Tenure','Balance','NumOfProducts','EstimatedSalary']].describe()

CreditScore           Age        Tenure        Balance  NumOfProducts  \
count  10000.000000  10000.000000  10000.000000   10000.000000   10000.000000   
mean     650.528800     38.921800      5.012800   76485.889288       1.530200   
std       96.653299     10.487806      2.892174   62397.405202       0.581654   
min      350.000000     18.000000      0.000000       0.000000       1.000000   
25%      584.000000     32.000000      3.000000       0.000000       1.000000   
50%      652.000000     37.000000      5.000000   97198.540000       1.000000   
75%      718.000000     44.000000      7.000000  127644.240000       2.000000   
max      850.000000     92.000000     10.000000  250898.090000       4.000000   

       EstimatedSalary  
count     10000.000000  
mean     100090.239881  
std       57510.492818  
min          11.580000  
25%       51002.110000  
50%      100193.915000  
75%      149388.247500  
max      199992.480000

In [124]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [125]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

#### Label Encoding the "Gender" column

In [126]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [127]:
print(X)
# Female - 0
# Male - 1

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


#### One Hot Encoding the "Geography" column

In [128]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [129]:
print(X)
# France  - 1,0,0
# Spain   - 0,0,1
# Germany - 0,1,0

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [130]:
X.shape

(10000, 12)

### Splitting the dataset into the Training set and Test set

In [131]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [132]:
X_train.shape, y_train.shape

((8000, 12), (8000,))

In [133]:
X_test.shape, y_test.shape

((2000, 12), (2000,))

#### Feature Scaling

In [134]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [135]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [136]:
 ann = Sequential([
     Dense(units = 6, activation = 'relu'),
     Dense(units = 6, activation = 'relu'),
     Dense(units = 1, activation = 'sigmoid'),
 ])

## Part 3 - Training the ANN

### Compiling the ANN

In [137]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [138]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7904
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4622 - accuracy: 0.7961
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4393 - accuracy: 0.8027
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4301 - accuracy: 0.8084
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4254 - accuracy: 0.8109
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4227 - accuracy: 0.8120
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4208 - accuracy: 0.8148
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4192 - accuracy: 0.8155
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4177 - accuracy: 0.8169
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4161 - accura

250/250 [==============================] - 0s 2ms/step - loss: 0.3345 - accuracy: 0.8658
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3339 - accuracy: 0.8650
Epoch 83/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3342 - accuracy: 0.8636
Epoch 84/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3342 - accuracy: 0.8649
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3343 - accuracy: 0.8644
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3340 - accuracy: 0.8636
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3342 - accuracy: 0.8654
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3342 - accuracy: 0.8637
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3340 - accuracy: 0.8636
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3341 - accuracy: 

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [139]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix and accuracy score

In [142]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1509   86]
 [ 197  208]]


0.8585

#### Predicting the result of a single observation

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

In [143]:
new_pred = ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))
print(new_pred)
if new_pred>= 0.5:
    print('The customer left the bank')
else:
    print('The customer stay in the bank')

1/1 [==============================] - 0s 19ms/step
[[0.03079371]]
The customer stay in the bank
